action_id: trunk-share-with-everyone
date: 2024-08-14 21:30:17
run: trunk config share --notify --allow-daemon-start=false
run_from: ""
trigger: .git/info/exclude
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1723671017
full_timestamp:
  nanos: 240897000
  seconds: 1723671017
trunk_version: 1.22.2
